### ISSUE TITLE
Repo contribution

### ISSUE THREAD

**Issue by hugsy** [0xADE1A1DE/AssemblyLine#14]
Hi! Thanks for your really great project!

I've been looking for something exactly like that for a while for a project of mine , and so I've forked and added a few improvements such as:
 - full Windows support
 - transition from `autoconf` to `cmake` as build system generator
 - integration to GH Actions for CI purposes
 - added a proper coding style + automatic code formatting
 - a few minor bugs fixed here and there (including a nasty one in `tokenizer.c`)

All my work is [here](https://github.com/hugsy/AssemblyLine) but in case some (or all) of those features might interest you I'm happy to PR. Let me know!

Cheers

**Comment by davidywu9** [comment]
Thank you so much for your contribution!
Feel free to submit a pull request anytime and the other authors and I will review the pull request. 

Cheers
